export const mockPros = [
  {
    id: "1",
    name: "James Wilson",
    tradeType: "electrician",
    headline: "Master Electrician · 15 Years Experience",
    location: "Manchester, UK",
    hourlyRate: 65,
    avgRating: 4.9,
    reviewCount: 142,
    completedJobs: 189,
    responseTime: "within 2 hours",
    verified: true,
    insuranceVerified: true,
    backgroundChecked: true,
    available: true,
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop&crop=face",
    skills: ["Rewiring", "Consumer units", "EV chargers", "Solar panels", "Smart home"],
    description: "Fully qualified master electrician with 15 years of experience. I specialise in domestic and commercial electrical work including full rewires, consumer unit replacements, and EV charger installations. All work certified and guaranteed.",
    portfolioImages: [
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop",
    ],
  },
  {
    id: "2",
    name: "Sarah Thompson",
    tradeType: "plumber",
    headline: "Certified Plumber & Heating Engineer",
    location: "London, UK",
    hourlyRate: 75,
    avgRating: 4.8,
    reviewCount: 98,
    completedJobs: 134,
    responseTime: "within 4 hours",
    verified: true,
    insuranceVerified: true,
    backgroundChecked: true,
    available: true,
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200&h=200&fit=crop&crop=face",
    skills: ["Boiler installation", "Central heating", "Bathroom fitting", "Emergency repairs", "Leak detection"],
    description: "Gas Safe registered plumber and heating engineer. Expert in boiler installations, central heating systems, and bathroom renovations. Emergency call-out available.",
    portfolioImages: [
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    ],
  },
  {
    id: "3",
    name: "Michael Davies",
    tradeType: "carpenter",
    headline: "Bespoke Carpenter & Joiner",
    location: "Birmingham, UK",
    hourlyRate: 55,
    avgRating: 4.95,
    reviewCount: 76,
    completedJobs: 91,
    responseTime: "within 24 hours",
    verified: true,
    insuranceVerified: true,
    backgroundChecked: false,
    available: true,
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
    skills: ["Fitted wardrobes", "Kitchen installation", "Hardwood floors", "Skirting boards", "Door hanging"],
    description: "Skilled carpenter and joiner with a passion for bespoke furniture and quality finishes. Specialising in fitted bedrooms, kitchens and hardwood flooring.",
    portfolioImages: [
      "https://images.unsplash.com/photo-1581428982868-e410dd047a90?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop",
    ],
  },
  {
    id: "4",
    name: "Robert Clarke",
    tradeType: "roofer",
    headline: "Expert Roofer & Flat Roof Specialist",
    location: "Leeds, UK",
    hourlyRate: 60,
    avgRating: 4.7,
    reviewCount: 54,
    completedJobs: 78,
    responseTime: "within 8 hours",
    verified: true,
    insuranceVerified: true,
    backgroundChecked: true,
    available: true,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    skills: ["Flat roofing", "Tile replacement", "Guttering", "Fascias & soffits", "Velux windows"],
    description: "Experienced roofer covering all aspects of roofing work. Specialising in flat roofing systems, tile work, and guttering. Free no-obligation quotes.",
    portfolioImages: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=300&fit=crop",
    ],
  },
  {
    id: "5",
    name: "Emma Patel",
    tradeType: "painter",
    headline: "Interior & Exterior Painting Specialist",
    location: "Bristol, UK",
    hourlyRate: 40,
    avgRating: 4.85,
    reviewCount: 112,
    completedJobs: 156,
    responseTime: "within 3 hours",
    verified: true,
    insuranceVerified: true,
    backgroundChecked: true,
    available: false,
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face",
    skills: ["Interior painting", "Exterior painting", "Wallpaper hanging", "Feature walls", "Commercial painting"],
    description: "Professional decorator with 10 years experience transforming homes and offices. Attention to detail and minimal disruption. Fully insured.",
    portfolioImages: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop",
    ],
  },
  {
    id: "6",
    name: "Tom Bradley",
    tradeType: "hvac",
    headline: "Gas Safe & F-Gas Certified HVAC Engineer",
    location: "Sheffield, UK",
    hourlyRate: 70,
    avgRating: 4.75,
    reviewCount: 67,
    completedJobs: 95,
    responseTime: "within 6 hours",
    verified: true,
    insuranceVerified: true,
    backgroundChecked: true,
    available: true,
    image: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=200&h=200&fit=crop&crop=face",
    skills: ["Air conditioning", "Heat pumps", "Underfloor heating", "Boiler servicing", "Ventilation systems"],
    description: "Gas Safe and F-Gas certified HVAC engineer. Specialising in air conditioning, heat pumps and underfloor heating. Annual service contracts available.",
    portfolioImages: [
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    ],
  },
];

export const mockReviews = [
  {
    id: "r1",
    reviewerName: "Alice Johnson",
    reviewerImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face",
    rating: 5,
    title: "Excellent work, very professional",
    comment: "James did a brilliant job rewiring our kitchen. He arrived on time, kept everything clean and tidy, and explained everything he was doing. Would definitely recommend and will use again.",
    date: "2025-04-15",
    qualityRating: 5,
    timelinessRating: 5,
    valueRating: 4,
    communicationRating: 5,
  },
  {
    id: "r2",
    reviewerName: "David Smith",
    reviewerImage: "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=100&h=100&fit=crop&crop=face",
    rating: 5,
    title: "Great service, highly recommended",
    comment: "Fixed our electrical fault quickly and efficiently. Very knowledgeable and fairly priced. Will use again for future work.",
    date: "2025-03-22",
    qualityRating: 5,
    timelinessRating: 5,
    valueRating: 5,
    communicationRating: 4,
  },
  {
    id: "r3",
    reviewerName: "Sophie Williams",
    reviewerImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    rating: 4,
    title: "Good work overall",
    comment: "Installed a new consumer unit and sorted out some faulty sockets. Work was done well and to code. Slight delay to start time but communicated well.",
    date: "2025-02-18",
    qualityRating: 5,
    timelinessRating: 3,
    valueRating: 4,
    communicationRating: 4,
  },
];

export const mockJobs = [
  {
    id: "j1",
    title: "Full bathroom renovation needed",
    tradeType: "plumber",
    location: "London, SW10",
    budget: 3500,
    budgetType: "fixed",
    urgency: "within 2 weeks",
    description: "Complete bathroom strip out and refit. New shower, bath, toilet and basin. Tiles to be fitted too. Looking for a reliable tradesperson.",
    quotesCount: 4,
    createdAt: "2025-05-14",
  },
  {
    id: "j2",
    title: "Kitchen electrical work",
    tradeType: "electrician",
    location: "Manchester, M14",
    budget: 800,
    budgetType: "fixed",
    urgency: "flexible",
    description: "New kitchen being fitted and need all electrical work done. Extra sockets, under cabinet lighting, extractor fan wiring.",
    quotesCount: 7,
    createdAt: "2025-05-13",
  },
  {
    id: "j3",
    title: "Leaking roof repair",
    tradeType: "roofer",
    location: "Leeds, LS6",
    budget: null,
    budgetType: "quote",
    urgency: "asap",
    description: "Water coming in through bedroom ceiling after rain. Need someone to assess and repair. Slate roof on Victorian terrace.",
    quotesCount: 2,
    createdAt: "2025-05-15",
  },
];

export const mockBookings = [
  {
    id: "b1",
    title: "Electrical inspection & report",
    tradesperson: { name: "James Wilson", trade: "Electrician", image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face" },
    homeowner: { name: "You", image: "" },
    scheduledDate: "2025-05-22T09:00:00",
    agreedPrice: 150,
    status: "confirmed",
    address: "14 Oak Street, Manchester, M14 5KL",
  },
  {
    id: "b2",
    title: "New boiler installation",
    tradesperson: { name: "Sarah Thompson", trade: "Plumber", image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100&h=100&fit=crop&crop=face" },
    homeowner: { name: "You", image: "" },
    scheduledDate: "2025-06-03T08:00:00",
    agreedPrice: 2200,
    status: "pending",
    address: "14 Oak Street, Manchester, M14 5KL",
  },
  {
    id: "b3",
    title: "Bedroom wardrobe fitting",
    tradesperson: { name: "Michael Davies", trade: "Carpenter", image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face" },
    homeowner: { name: "You", image: "" },
    scheduledDate: "2025-04-10T08:30:00",
    agreedPrice: 850,
    status: "completed",
    address: "14 Oak Street, Manchester, M14 5KL",
  },
];

export const mockConversations = [
  {
    id: "c1",
    participant: {
      name: "James Wilson",
      image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face",
      trade: "Electrician",
    },
    lastMessage: "I can come out on Thursday morning, does that work for you?",
    lastMessageAt: "2025-05-18T14:30:00",
    unread: 2,
  },
  {
    id: "c2",
    participant: {
      name: "Sarah Thompson",
      image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100&h=100&fit=crop&crop=face",
      trade: "Plumber",
    },
    lastMessage: "The quote for the bathroom would be £2,400 all in.",
    lastMessageAt: "2025-05-17T10:15:00",
    unread: 0,
  },
  {
    id: "c3",
    participant: {
      name: "Michael Davies",
      image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
      trade: "Carpenter",
    },
    lastMessage: "Thanks for the great review! Happy to help again anytime.",
    lastMessageAt: "2025-05-14T16:45:00",
    unread: 0,
  },
];

export const mockMessages: Record<string, Array<{id: string; senderId: string; content: string; createdAt: string}>> = {
  c1: [
    { id: "m1", senderId: "you", content: "Hi James, I need someone to look at my consumer unit.", createdAt: "2025-05-18T13:00:00" },
    { id: "m2", senderId: "them", content: "Hi! Happy to help. Can you describe what the issue is?", createdAt: "2025-05-18T13:15:00" },
    { id: "m3", senderId: "you", content: "Some circuits keep tripping, especially in the kitchen. It's a 20 year old unit.", createdAt: "2025-05-18T13:20:00" },
    { id: "m4", senderId: "them", content: "Sounds like it might need replacing. I'd need to come and do a visual inspection first. I charge £75 for an inspection which comes off any work.", createdAt: "2025-05-18T13:35:00" },
    { id: "m5", senderId: "you", content: "That sounds fair. When are you available?", createdAt: "2025-05-18T14:00:00" },
    { id: "m6", senderId: "them", content: "I can come out on Thursday morning, does that work for you?", createdAt: "2025-05-18T14:30:00" },
  ],
};
